### ISSUE TITLE
Setup.py needs to be inside the 'inner' migfinder folder

### ISSUE THREAD

**Issue by susheelbhanu** [maribuon/MIG-finder#2]
- For the installation to work, we had to do the following:

1. download the package files
2. unzip the folder
3. copy the `setup.py` file inside the `migfinder-master/migfinder/` folder
4. `cd migfinder-master/migfinder`
5. run `make`

**Comment by maribuon** [comment]
Thank you so much for reporting this! I have updated the repository and the README accordingly!
