### ISSUE TITLE
Failed to open sequence file

### ISSUE THREAD

**Issue by susheelbhanu** [maribuon/MIG-finder#3]
- After successful installation we tried to run a test dataset as follows:

```
import migfinder as mf
mf.main("10_MG_Paul_S9.fna")
```

We are running into the following issue:
```
hattci.out -b -s 1000 -t 6 10_MG_Paul_S9.fna 10_MG_Paul_S9.tmp > 10_MG_Paul_S9.hmmlog
mv: cannot stat ‘hmmresults/outHattCI.fasta’: No such file or directory
HattCI done!
Failed to open sequence file ../hmmresults/10_MG_Paul_S9_hattci.fasta for reading

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "migfinder.py", line 890, in main
    infernal(fastafile="../hmmresults/"+out+"_hattci.fasta", out=out)
  File "migfinder.py", line 76, in infernal
    filein = open(out+".tmp")
IOError: [Errno 2] No such file or directory: '10_MG_Paul_S9.tmp'
```

Note: please add to instructions that the fasta file has to be within the `migfinder-master/migfinder` folder as well. 

Thank you for your help!

-Susheel

**Comment by susheelbhanu** [comment]
Partially fixed by using the "updated" python script (attached). 
[migfinder.py.txt](https://github.com/maribuon/migfinder/files/5194089/migfinder.py.txt)

Issues still remain with respect to `csv`.

**Comment by maribuon** [comment]
Hi Susheel!
Thank you for the note on the documentation, I have updated it accordingly!
I am sorry you are still facing issues, can you elaborate a little on the csv problem please?

**Comment by susheelbhanu** [comment]
Hey @maribuon

I no longer have the above issue, but for some reason it cannot find the "cm_model/selection109_oriR.cm" file. 

```
>>> mf.main("10_MG_Paul_S9.fna")
HattCI done!

Error: CM file cm_model/selection109_oriR.cm not found (nor an .i1m binary of it)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "migfinder.py", line 891, in main
    infernal(fastafile="../hmmresults/"+out+"_hattci.fasta", out=out)
  File "migfinder.py", line 77, in infernal
    filein = open(out+".tmp")
IOError: [Errno 2] No such file or directory: '10_MG_Paul_S9.tmp'
```

I can confirm that the file exists. It may be the problem that I'm running it from inside the internal `migfinder` folder.

**Comment by susheelbhanu** [comment]
I tried changing the path in the python script itself, below
```cm_model= pkg_resources.resource_filename('migfinder', '../cm_model/selection109_oriR.cm')```

It can now detect the file, but for some reason says that there are no hits. I know there are attC sequence 'cos I used BLAST to confirm. 
```
HattCI done!
attC hits from pipeline: 0
Infernal done!
No attC found, skipping Prodigal step...
```

**Comment by maribuon** [comment]
Hi @susheelbhanu ,
there are unfortunately too many relative links on the  script. Can you update the path to cm_model/selection109_oriR.cm to its full path? Doe sit work then?
Best wishes,
Mariana

**Comment by maribuon** [comment]
Hi again @susheelbhanu ,
The output you gave above seems correct. Unfortunately indicating that our model cannot find any attC site.
I suggest that you
1. check the input
2. check the folder structure to see if you get hits from HattCI (does not seem so from the above) If you do, it may be that the secondary structure is has not been validated?
Best,
Mariana

**Comment by susheelbhanu** [comment]
@maribuon 

I have the following hits (head example) in the HattCI file
```
>10_MG_Paul_S9_contig_5_95010_95072 Vscore: 3.182062
ATTCAACATCAACGTTGACCGACGCCGACTTACCGCCGGAAGCCTTAAGGCCATCGGTTGTTA

>10_MG_Paul_S9_contig_5_193968_194060 Vscore: 0.551134
CCATAACCTGTCGTCCGAGCCAATACAGTGCATCGGCCATCGCGCATGCCGTTGAGGATGCCGACGCGCATCTGCTTAATCTTAATGTTACAG

>10_MG_Paul_S9_contig_5_293663_293791 Vscore: 4.553633
CTATAACAACAACCGTCAGGGCGGCTACAACAACAACCGTCAGGGTGGCTACAACAACCGCCAGCAGGGAGGTTACAACAACAACCGTCAGCAGGGCGGCTATAACAACCGTCAGCAGGGCGGTTACAA

>10_MG_Paul_S9_contig_5_297887_297958 Vscore: 3.567692
AGGTAACCTTCAGCTCGACCTGGCAATGCCGTTCCTCCGCGAACTCCACGCCAACCTCAACCTCGGTTACGA

>10_MG_Paul_S9_contig_5_299042_299109 Vscore: 2.132432
TACCAACATCCAGGCCCACATGGTGGGACACCCCGCTTACAGCTTCTACGTTTACCAGCAGGTTTACG

>10_MG_Paul_S9_contig_5_313361_313414 Vscore: 0.630437
GAAGAACATCGCGCTCAAGATGTTTTCGCGCGGAATGTTGAACAACAGTTCCGA

>10_MG_Paul_S9_contig_5_345002_344950 Vscore: 0.153291 REVERSED
GAAGAACATCCTCTTTGAGCCCGACAACGGACAGGGTACCGAAGTTGTTCCCG

>10_MG_Paul_S9_contig_5_202188_202124 Vscore: 0.848828 REVERSED
ACCTAACGAATTCTTCATGGACTTCATCGCGCTTGCGCCAAACCTGCCGCAAGCCAAGGTTCAGA

>10_MG_Paul_S9_contig_5_61535_61466 Vscore: 0.798051 REVERSED
CAGTAACAAACGCTCCACCCAAATCCCCGCGTTAGCGCCAAAGCTGCAGAGCAGCTTAATAATGTTAGGC

>10_MG_Paul_S9_contig_5_44742_44649 Vscore: 0.635288 REVERSED
CGGTAACAAGTTGTTCAGCAGCCATTATCATCGCTACCAAAGGCGATGTGGCTGGCAAGGGGTCAGTGTCCAAGTCGTTATAAATTAGTTAAAC
```

I suppose the secondary structures are not validated. Could you please provide a test file where we could see what this looks like? Something where you have known attC with validated secondary structures.

Thank you

**Comment by maribuon** [comment]
Most certainly! I can do so tonight, I need access to my old laptop for that :)

Just some insights: the Vscores are quite low. But that is not necessarily a show stopper from our experience.

**Comment by susheelbhanu** [comment]
Thank you!

**Comment by maribuon** [comment]
Hi @susheelbhanu ,

here is one of the files we used in the paper. Our final catalogue contains 10 attC sites fro this file, which mean the files should be 10 or more attC sites found by the pipeline.

[mgm4570162.3.050.1.fasta.zip](https://github.com/maribuon/migfinder/files/5197432/mgm4570162.3.050.1.fasta.zip)

Let me know what you find!

Best wishes,
Mariana

**Comment by susheelbhanu** [comment]
@maribuon Thank you for the file. It of course has attC hits 😉 
```
HattCI done!
attC hits from pipeline: 7
```

However, I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "migfinder.py", line 893, in main
    posproc(fastafile, out, k_cm)
  File "migfinder.py", line 298, in posproc
    fhmm = list(csv.reader(open(tmp, 'rb'),delimiter='\t'))
IOError: [Errno 2] No such file or directory: 'hmmresults/migfinder_test.hmm'
```

The file is written, but outside of the `hmmresults` folder. I manually copied it to the folder, and it ran fine. Could you please update the code accordingly. 
```
>>> mf.main("migfinder_test.fasta")
HattCI done!
attC hits from pipeline: 7
Infernal done!
Prodigal done! Staring pos-processing...
Pos-processing done!
```

Suggestion: May be useful for future users if you could provide the same file as a `test.fasta` file, so they know the tool works 😄 

Guess our sequences didn't have them after all. Thanks again for all the help!

**Comment by maribuon** [comment]
Hi @susheelbhanu ,
Thanks for the suggestion. 
Re not having attC sites on your data. My understanding is that the secondary structure is very important for a functional attC site. On our first paper (HattCI) we did not considered it and had to increase the threshold of Vscore to something around 20 to efficiently remove FP. On our second paper, with secondary structure validation we could remove the Vscore threshold, and our FP discovery rate is nearly null.
With that said, our cm model is a bit old now. You may consider updating the model (I would recommend hand picked attC sites only) and verify if your data really doesn’t contain any attC sites.
Best wishes and good luck on your research!
Mariana
