### ISSUE TITLE
HattCI segfault

### ISSUE THREAD

**Issue by nebfield** [maribuon/MIG-finder#4]
Hello,

Thanks for publishing this software, it looks really cool! 😁 

I'm getting a strange error about HattCI using the example data you uploaded in #3:

```
Python 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:56:06)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import migfinder as mf
>>> mf.main("mgm4570162.3.050.1.fasta")
sh: line 1:  5816 Segmentation fault      (core dumped) hattci.out -b -s 1000 -t 6 mgm4570162.3.050.1.fasta mgm4570162.3.050.1.tmp > mgm4570162.3.050.1.hmmlog
mv: cannot stat ‘hmmresults/outHattCI.fasta’: No such file or directory
HattCI done!
Failed to open sequence file ../hmmresults/mgm4570162.3.050.1_hattci.fasta for reading

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/bwingfield/repos/migfinder/migfinder/migfinder.py", line 890, in main
    infernal(fastafile="../hmmresults/"+out+"_hattci.fasta", out=out)
  File "/users/bwingfield/repos/migfinder/migfinder/migfinder.py", line 76, in infernal
    filein = open(out+".tmp")
IOError: [Errno 2] No such file or directory: 'mgm4570162.3.050.1.tmp'
```

`hattci.out` segfaults and then the rest of the script errors from there. However, if I run the same command outside of migfinder it's fine:

```
$ hattci.out -b -s 1000 -t 6 mgm4570162.3.050.1.fasta mgm4570162.3.050.1.tmp > mgm4570162.3.050.1.hmm.log
$ cat mgm4570162.3.050.1.hmm.log
Mbases processed: 29.916034
Sequences read: 23682
Sequences processed: 23682
Hits (top strand): 635
Hits (bottom strand): 651
```

Any help would be appreciated.

Cheers,
Ben

**Comment by maribuon** [comment]
Hi Ben,
thanks a lot for your interesting in migfinder and the detailed report of the error!
I believe the error to be generated by the relative paths in the code. I will have a look at it tonight and get back to you as soon as possible.
Best wishes,
Mariana

**Comment by maribuon** [comment]
Hi again, Ben!
I believe you need to provide the full path to your fasta even if it is in the directory where you are working from. Can you try that and let me know if it works, please?
Sorry for the inconvenience.
Mariana 

P.S. I have updated the documentation to reflect it. So, thank you very much for reporting it! :)

**Comment by nebfield** [comment]
Hi Mariana,

Thanks for your help :grin: I'm getting a different error about a missing model when I give a full path, but I think it's related to paths again (the file definitely exists).

```
(mig) [bwingfield@login2 [kelvin2] migfinder-master]$ pwd
/users/bwingfield/repos/migfinder-master
(mig) [bwingfield@login2 [kelvin2] migfinder-master]$ python
Python 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:56:06)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import migfinder as mf
m>>> mf.main("/users/bwingfield/repos/migfinder-master/test/mgm4570162.3.050.1.fasta")
HattCI done!

Error: CM file migfinder/cm_model/selection109_oriR.cm not found (nor an .i1m binary of it)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "migfinder/migfinder.py", line 890, in main
  File "migfinder/migfinder.py", line 76, in infernal
IOError: [Errno 2] No such file or directory: 'mgm4570162.3.050.1.tmp'
```

I had some trouble installing migfinder, and I think this could be related to that. When I try to install migfinder with `pip` (python 2.7):

```
(mig) [bwingfield@login2 [kelvin2] migfinder-master]$ pip install --user -e migfinder
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Obtaining file:///users/bwingfield/repos/migfinder-master/migfinder
ERROR: Could not find a version that satisfies the requirement Bio (from migfinder==1.0) (from versions: none)
ERROR: No matching distribution found for Bio (from migfinder==1.0)
```

I can install OK using `python3 -m pip install --user -e migfinder` (suggested in #1) but this installs the package into my python3 site-packages, where python2 can't read from. If I try to run migfinder in python3:

```
(mig) [bwingfield@login2 [kelvin2] repos]$ python3
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import migfinder as mf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/bwingfield/repos/migfinder-master/migfinder/migfinder.py", line 286
    print "attC hits from pipeline: "+str(len(table))
                                    ^
SyntaxError: invalid syntax
```

So I think that migfinder requires python 2.7 to run. I've just been importing migfinder successfully by running python in the `/users/bwingfield/repos/migfinder-master` directory. Can I double check with you the best process to reinstall migfinder?

Thanks,
Ben

**Comment by maribuon** [comment]
Hi again Ben @nebfield ,

Indeed this is probably related to the installation. I have started installation from scratch on my computer and found an issue with Bio. I have updated the setup.py. Can you remove migfinder and install it again, using python 2.7 and the files here on GitHub, please?

I am really sorry for the inconvenience!

Best wishes,
Mariana

**Comment by nebfield** [comment]
I can install with python 2.7 now! 🎉 Thanks for the update 

I have found a workaround for the missing model error (`Error: CM file migfinder/cm_model/selection109_oriR.cm not found (nor an .i1m binary of it)`). You have to run migfinder in the top-level directory that the git repo is cloned to, for example:

```
(mig) [bwingfield@login2 [kelvin2] repos]$ pwd
/users/bwingfield/repos
(mig) [bwingfield@login2 [kelvin2] repos]$ python
Python 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:56:06)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import migfinder as mf
>>> mf.main("/users/bwingfield/repos/migfinder/exampleData/test.fasta")
HattCI done!
attC hits from pipeline: 7
Infernal done!
Prodigal done! Staring pos-processing...
Pos-processing done!
```

Runs OK, but running outside of this specific directory fails:

```
(mig) [bwingfield@login2 [kelvin2] exampleData]$ pwd
/users/bwingfield/repos/migfinder/exampleData
(mig) [bwingfield@login2 [kelvin2] migfinder]$ python
Python 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:56:06)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import migfinder as mf
>>> mf.main("/users/bwingfield/repos/migfinder/exampleData/test.fasta")
HattCI done!

Error: CM file migfinder/cm_model/selection109_oriR.cm not found (nor an .i1m binary of it)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "migfinder/migfinder.py", line 890, in main
    infernal(fastafile="../hmmresults/"+out+"_hattci.fasta", out=out)
  File "migfinder/migfinder.py", line 76, in infernal
    filein = open(out+".tmp")
IOError: [Errno 2] No such file or directory: 'test.tmp'
```

I'm not a Python expert (I prefer R) but I think a fix would be to [get the model path from the absolute install directory path](https://stackoverflow.com/questions/247770/how-to-retrieve-a-modules-path). For example:

```
(mig) [bwingfield@login2 [kelvin2] repos]$ pip list --user
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package   Version Location
--------- ------- -------------------------------------------
migfinder 1.0     /users/bwingfield/repos/migfinder/migfinder
(mig) [bwingfield@login2 [kelvin2] repos]$ python
Python 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:56:06)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import migfinder as mf
>>> mf.__file__
'/users/bwingfield/repos/migfinder/migfinder/migfinder.pyc'
```

But I could be totally wrong! 😅 

Also, I'm not sure how I would run `migfinder` on multiple samples, since some output files have the same name for every run (e.g. `hmmresults`). Can I suggest an additional argument for the main function to include specifying an output directory? 

Apologies for this gigantic wall of text and thanks again for all of your help!

**Comment by maribuon** [comment]
Hi Ben!
Very nice exploratory work with the path! What I am confused about is that I can successfully run  migfinder on any path on my computer :/  ~~In fact, even when I use another computer, I get the correct path if I do:~~


~~python~~
~~import pkg_resources~~
~~pkg_resources.resource_filename('migfinder', 'cm_model/selection109_oriR.cm')~~


~~However, it does seem another user had the same problem. (I also prefer R!)~~
~~Can you report what does the above spill out for you, please?~~

I have used a variation of what you send me, and it does work on my computer. The previous version also did. So I would like to ask you to re-install migfinder and tell me if it works now (really hope so). If not, a very ad-hoc solution is for you to edit line 22 to give your path, i.e. cm_model = '/users/bwingfield/repos/migfinder/migfinder/cm_model/selection109_oriR.cm'
 
####
Re how to run it for multiple samples, I have done so by creating one dir per fastafile and running migfinder inside each one of them. If the path for cm is fixed these files could be anywhere. However, you can also run them from the same dir,  each output will have one name, the common names are folder which separate each step of the pipeline, i.e. hmmresultd (hattci), cmresults (infernal) and orfresults (prodigal). The resulting files will be fastaname.results.

Let me know how it goes, very happy to help :)

**Comment by nebfield** [comment]
That's weird, I seem to get the correct path:

```
(mig) [bwingfield@login1(kelvin2) ~]$ python
Python 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:56:06)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> pkg_resources.resource_filename('migfinder', 'cm_model/selection109_oriR.cm')
'/users/bwingfield/repos/migfinder/migfinder/cm_model/selection109_oriR.cm'
```

Maybe [`pkgutil.get_data` would be a good approach?](https://stackoverflow.com/questions/39104/finding-a-file-in-a-python-module-distribution)

I'll try the latest changes you've made 😁

**Comment by maribuon** [comment]
Very weird! The latest changes avoid pkg_resource altogether and use os instead, which is more basic, hence stable, package. I think it should work now. Looking forward to hear how it goes! :)

**Comment by nebfield** [comment]
Perfect, with your most recent changes I can run `migfinder` anywhere:

```
(mig) [bwingfield@login1(kelvin2) test]$ pwd
/users/bwingfield/repos/test
(mig) [bwingfield@login1(kelvin2) test]$ python
Python 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:56:06)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import migfinder as mf
>>> mf.main("/users/bwingfield/repos/test/test.fasta")
HattCI done!
attC hits from pipeline: 7
Infernal done!
Prodigal done! Staring pos-processing...
Pos-processing done!
>>>
```

Thanks for your help 😁

**Comment by maribuon** [comment]
Happy it worked! Let me know if you have questions on how to interpret the results :)
