### ISSUE TITLE
Error: CM file cm_model/selection109_oriR.cm not found (nor an .i1m binary of it)

### ISSUE THREAD

**Issue by tigerxu** [maribuon/MIG-finder#6]
Hi Mariana,

I met a problem when I test a FASTA genome using migfinder. I attached the running message and my working directory. Would you like to give me some advice to fix it?

Thank you very much in advance!

Zhuofei

(migfinder) [couser@cs migfinder]$ python
Python 2.7.15 | packaged by conda-forge | (default, Mar  5 2020, 14:56:06) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import migfinder as mf
>>> mf.main("/home/couser/install/migfinder/migfinder/NZ_CP024655.fasta")
HattCI done!

Error: CM file cm_model/selection109_oriR.cm not found (nor an .i1m binary of it)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "migfinder.py", line 893, in main
    infernal(fastafile="../hmmresults/"+out+"_hattci.fasta", out=out)
  File "migfinder.py", line 79, in infernal
    filein = open(out+".tmp")
IOError: [Errno 2] No such file or directory: 'NZ_CP024655.tmp'
>>> 

The structure of my working directory 
(migfinder) [couser@cs migfinder]$ ll
total 2444
drwxr-xr-x 3 couser user      40 Dec  4 14:40 build
drwxr-xr-x 2 couser user      42 Dec  3 17:33 cm_model
drwxr-xr-x 2 couser user      10 Dec  4 14:43 cmresults
drwxr-xr-x 2 couser user      45 Dec  4 14:40 dist
drwxr-xr-x 2 couser user     103 Dec  4 15:01 hmmresults
-rw-r--r-- 1 couser user      24 Dec  3 17:33 __init__.py
-rw-r--r-- 1 couser user     148 Dec  4 14:57 __init__.pyc
drwxr-xr-x 2 couser user     158 Dec  4 14:44 migfinder.egg-info
-rw-r--r-- 1 couser user   31688 Dec  4 14:59 migfinder.py
-rw-r--r-- 1 couser user   19743 Dec  4 15:00 migfinder.pyc
-rw-r--r-- 1 couser user 2433178 Dec  4 14:27 NZ_CP024655.fasta
-rw-r--r-- 1 couser user     514 Dec  3 17:33 setup.py

**Comment by maribuon** [comment]
Hi @tigerxu ,
thank you for using migfinder :)
And I am sorry to hear you run into issues. In fact, this should have been solved previously.
Can you confirm to me that you have installed migfinder following these guidelines:

_Download and uncompress the files provided here. In the directory where migfinder directory is located run:_

_user@machine:~$ pip install -e migfinder_
?

**Comment by maribuon** [comment]
Hi @tigerxu ,
just wondering if you installed migfinder as described above?
I am keen to help you to get migfinder to work!
Bets wishes,
Mariana

**Comment by tigerxu** [comment]
Hi Mariana,
Thanks a lot for your suggestion! I will follow your advice to install migfinder. I will let you know as soon as possible this week.
best,
zhuofei



---Original---

**Comment by tigerxu** [comment]
Hi Mariana,

many thanks for your guide. It works!

Best wishes,
Zhuofei

**Comment by maribuon** [comment]
Very pleased to hear! :)
Do get in touch if you find other issues.
And very good luck with research!
